/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.UIManager;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author letan
 */
public class MainGUI extends javax.swing.JFrame {

    private final Color BG_NORMAL = Color.WHITE;
    private final Color TEXT_NORMAL = new Color(155, 159, 173);
    private final Color BG_HOVER = new Color(232, 242, 254); // xanh nhạt
    private final Color TEXT_HOVER = new Color(33, 115, 255);

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form MainGUI
     */

    /**
     * Scale ảnh với chất lượng cao sử dụng multi-step scaling
     * Progressive scaling cho kết quả tốt hơn khi scale down nhiều
     */

    public MainGUI() {
        initComponents();
        // Scale logo sau khi UI được init
        SwingUtilities.invokeLater(() -> {
            //
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoFrame = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        leftSide = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        topSide = new javax.swing.JPanel();
        mainSide = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1400, 820));

        jPanel1.setBackground(new java.awt.Color(245, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 223, 229)));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 820));
        jPanel1.setLayout(new java.awt.BorderLayout());

        logoFrame.setBackground(new java.awt.Color(255, 255, 255));
        logoFrame.setPreferredSize(new java.awt.Dimension(248, 248));
        logoFrame.setLayout(new java.awt.BorderLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/Untitled design (2).png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(248, 248));
        logoFrame.add(logo, java.awt.BorderLayout.CENTER);

        jPanel1.add(logoFrame, java.awt.BorderLayout.PAGE_START);

        leftSide.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout leftSideLayout = new javax.swing.GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(
                leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 248, Short.MAX_VALUE));
        leftSideLayout.setVerticalGroup(
                leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1426, Short.MAX_VALUE));

        jPanel1.add(leftSide, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(246, 247, 248));
        jPanel2.setLayout(new java.awt.BorderLayout());

        topSide.setBackground(new java.awt.Color(255, 255, 255));
        topSide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 223, 229)));
        topSide.setPreferredSize(new java.awt.Dimension(1150, 80));

        javax.swing.GroupLayout topSideLayout = new javax.swing.GroupLayout(topSide);
        topSide.setLayout(topSideLayout);
        topSideLayout.setHorizontalGroup(
                topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1394, Short.MAX_VALUE));
        topSideLayout.setVerticalGroup(
                topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 78, Short.MAX_VALUE));

        jPanel2.add(topSide, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout mainSideLayout = new javax.swing.GroupLayout(mainSide);
        mainSide.setLayout(mainSideLayout);
        mainSideLayout.setHorizontalGroup(
                mainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1396, Short.MAX_VALUE));
        mainSideLayout.setVerticalGroup(
                mainSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1596, Short.MAX_VALUE));

        jPanel2.add(mainSide, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhacMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnKhacMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_btnKhacMouseEntered

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        // </editor-fold>
        // try {
        // UIManager.setLookAndFeel( new FlatMacLightLaf() );
        // } catch( Exception ex ) {
        // System.err.println( "Failed to initialize LaF" );
        // }

        /* Create and display the form */
        // FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel leftSide;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoFrame;
    private javax.swing.JPanel mainSide;
    private javax.swing.JPanel topSide;
    // End of variables declaration//GEN-END:variables
}
