/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author letan
 */
public class TourPanel extends javax.swing.JPanel {

    /**
     * Creates new form TourPanel
     */
    public TourPanel() {
        initComponents();
       
    }
    
//    // Thêm nội dung test để xem panel có hiển thị không
//    private void addTestContent() {
//        setLayout(new java.awt.BorderLayout());
//        
//        javax.swing.JLabel lblTitle = new javax.swing.JLabel("QUẢN LÝ TOUR");
//        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24));
//        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lblTitle.setForeground(new java.awt.Color(41, 128, 185));
//        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));
//        
//        add(lblTitle, java.awt.BorderLayout.NORTH);
//        
//        javax.swing.JLabel lblContent = new javax.swing.JLabel("Nội dung quản lý tour sẽ ở đây");
//        lblContent.setFont(new java.awt.Font("Segoe UI", 0, 16));
//        lblContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        lblContent.setForeground(new java.awt.Color(100, 100, 100));
//        
//        add(lblContent, java.awt.BorderLayout.CENTER);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Tour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(514, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
